ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SERVER';

ALTER TABLE "Product"
ADD COLUMN "averagePrepTimeMins" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN "prepTimeSamples" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Order"
ADD COLUMN "estimatedPrepMinutes" INTEGER,
ADD COLUMN "estimatedReadyAt" TIMESTAMP(3),
ADD COLUMN "actualPrepMinutes" INTEGER,
ADD COLUMN "preparationStartedAt" TIMESTAMP(3),
ADD COLUMN "readyAt" TIMESTAMP(3),
ADD COLUMN "servedAt" TIMESTAMP(3);
