import { Role } from '@prisma/client'
import { PermissionItem } from './types'

export const cashierPermissions: PermissionItem[] = [
  { key: 'POS_ACCESS', name: 'Point de Vente (POS)', desc: 'Prendre des commandes, encaisser les paiements, gérer le panier local.', module: 'commercial_pos', category: 'Opérations' },
  { key: 'CASH_DRAWER_ACCESS', name: 'Tiroir-caisse physique', desc: 'Ouvrir le tiroir-caisse manuellement et voir le montant attendu en caisse.', module: 'commercial_pos', category: 'Opérations' },
  { key: 'pos.orders_view', name: 'Historique des Commandes', desc: "Consulter toutes les commandes enregistrées dans l'établissement.", module: 'commercial_pos', category: 'Opérations' },
  { key: 'pos.orders_refund', name: 'Remboursements', desc: "Annuler des commandes et gérer les retours d'argent.", module: 'commercial_pos', category: 'Actions' },
  { key: 'pos.discounts', name: 'Appliquer des remises', desc: 'Faire des rabais en pourcentage ou montant fixe.', module: 'commercial_pos', category: 'Actions' },
  { key: 'pos.gift_cards', name: 'Cartes cadeaux', desc: 'Émettre et encaisser par cartes cadeaux.', module: 'commercial_pos', category: 'Opérations' },
  { key: 'pos.shift_open', name: 'Ouvrir session caisse', desc: 'Déclarer le fond de caisse initial le matin.', module: 'commercial_pos', category: 'Opérations' },
  { key: 'pos.shift_close', name: 'Clôturer session caisse', desc: 'Compter et valider la caisse en fin de journée.', module: 'commercial_pos', category: 'Opérations' },
  { key: 'pos.split_bill', name: "Diviser l'addition", desc: 'Séparer les tickets de caisse par client.', module: 'commercial_pos', category: 'Actions' },
  { key: 'pos.print_ticket', name: 'Réimprimer ticket', desc: 'Sortir un duplicata du reçu client.', module: 'commercial_pos', category: 'Actions' },
  { key: 'pos.offline_mode', name: 'Mode hors-ligne', desc: 'Vendre sur le POS sans connexion internet active.', module: 'commercial_pos', category: 'Système' },
  { key: 'pos.price_override', name: 'Surcharger prix', desc: "Modifier le prix de vente d'un plat directement au POS.", module: 'commercial_pos', category: 'Actions' },
  { key: 'pos.void_item', name: 'Supprimer article panier', desc: "Retirer un article d'un ticket de caisse en cours de saisie.", module: 'commercial_pos', category: 'Actions' },
  { key: 'pos.void_order', name: 'Annuler commande active (Void)', desc: 'Supprimer ou annuler complètement une commande en cours.', module: 'commercial_pos', category: 'Actions' },
  { key: 'pos.delete_order', name: 'Supprimer commande definitivement', desc: 'Supprimer une commande de la base de données.', module: 'commercial_pos', category: 'Actions' },
  { key: 'pos.reopen_order', name: 'Réouvrir une commande fermée', desc: 'Réouvrir une commande déjà réglée ou terminée.', module: 'commercial_pos', category: 'Actions' },
  { key: 'pos.tax_exempt', name: 'Exemptions de taxe', desc: 'Appliquer un profil de commande exempté de TVA.', module: 'commercial_pos', category: 'Actions' },
  { key: 'pos.customer_assign', name: 'Associer client', desc: 'Lier une fiche client à une commande POS.', module: 'commercial_pos', category: 'Opérations' }
]

export const cashierDefaultPermissions: Record<Role, Record<string, boolean>> = {
  RESTAURATEUR: {
    POS_ACCESS: true,
    CASH_DRAWER_ACCESS: true,
    'pos.orders_view': true,
    'pos.orders_refund': true,
    'pos.discounts': true,
    'pos.gift_cards': true,
    'pos.shift_open': true,
    'pos.shift_close': true,
    'pos.split_bill': true,
    'pos.print_ticket': true,
    'pos.offline_mode': true,
    'pos.price_override': true,
    'pos.void_item': true,
    'pos.void_order': true,
    'pos.delete_order': true,
    'pos.reopen_order': true,
    'pos.tax_exempt': true,
    'pos.customer_assign': true
  },
  MANAGER: {
    POS_ACCESS: true,
    CASH_DRAWER_ACCESS: true,
    'pos.orders_view': true,
    'pos.orders_refund': true,
    'pos.discounts': true,
    'pos.gift_cards': true,
    'pos.shift_open': true,
    'pos.shift_close': true,
    'pos.split_bill': true,
    'pos.print_ticket': true,
    'pos.offline_mode': true,
    'pos.price_override': true,
    'pos.void_item': true,
    'pos.void_order': true,
    'pos.delete_order': true,
    'pos.reopen_order': true,
    'pos.tax_exempt': true,
    'pos.customer_assign': true
  },
  CASHIER: {
    POS_ACCESS: true,
    CASH_DRAWER_ACCESS: true,
    'pos.orders_view': true,
    'pos.orders_refund': false,
    'pos.discounts': false,
    'pos.gift_cards': true,
    'pos.shift_open': true,
    'pos.shift_close': true,
    'pos.split_bill': true,
    'pos.print_ticket': true,
    'pos.offline_mode': true,
    'pos.price_override': false,
    'pos.void_item': true,
    'pos.void_order': false,
    'pos.delete_order': false,
    'pos.reopen_order': false,
    'pos.tax_exempt': false,
    'pos.customer_assign': true
  },
  SERVER: {
    POS_ACCESS: true,
    CASH_DRAWER_ACCESS: false,
    'pos.orders_view': true,
    'pos.orders_refund': false,
    'pos.discounts': false,
    'pos.gift_cards': false,
    'pos.shift_open': false,
    'pos.shift_close': false,
    'pos.split_bill': false,
    'pos.print_ticket': false,
    'pos.offline_mode': false,
    'pos.price_override': false,
    'pos.void_item': true,
    'pos.void_order': false,
    'pos.delete_order': false,
    'pos.reopen_order': false,
    'pos.tax_exempt': false,
    'pos.customer_assign': true
  },
  KITCHEN: {
    POS_ACCESS: false,
    CASH_DRAWER_ACCESS: false,
    'pos.orders_view': false,
    'pos.orders_refund': false,
    'pos.discounts': false,
    'pos.gift_cards': false,
    'pos.shift_open': false,
    'pos.shift_close': false,
    'pos.split_bill': false,
    'pos.print_ticket': false,
    'pos.offline_mode': false,
    'pos.price_override': false,
    'pos.void_item': false,
    'pos.void_order': false,
    'pos.delete_order': false,
    'pos.reopen_order': false,
    'pos.tax_exempt': false,
    'pos.customer_assign': false
  },
  DELIVERY: {
    POS_ACCESS: true,
    CASH_DRAWER_ACCESS: false,
    'pos.orders_view': true,
    'pos.orders_refund': false,
    'pos.discounts': false,
    'pos.gift_cards': false,
    'pos.shift_open': false,
    'pos.shift_close': false,
    'pos.split_bill': false,
    'pos.print_ticket': false,
    'pos.offline_mode': false,
    'pos.price_override': false,
    'pos.void_item': false,
    'pos.void_order': false,
    'pos.delete_order': false,
    'pos.reopen_order': false,
    'pos.tax_exempt': false,
    'pos.customer_assign': true
  },
  LIVREUR: {
    POS_ACCESS: true,
    CASH_DRAWER_ACCESS: false,
    'pos.orders_view': false,
    'pos.orders_refund': false,
    'pos.discounts': false,
    'pos.gift_cards': false,
    'pos.shift_open': false,
    'pos.shift_close': false,
    'pos.split_bill': false,
    'pos.print_ticket': false,
    'pos.offline_mode': false,
    'pos.price_override': false,
    'pos.void_item': false,
    'pos.void_order': false,
    'pos.delete_order': false,
    'pos.reopen_order': false,
    'pos.tax_exempt': false,
    'pos.customer_assign': false
  },
  ADMIN: {
    POS_ACCESS: true,
    CASH_DRAWER_ACCESS: true,
    'pos.orders_view': true,
    'pos.orders_refund': true,
    'pos.discounts': true,
    'pos.gift_cards': true,
    'pos.shift_open': true,
    'pos.shift_close': true,
    'pos.split_bill': true,
    'pos.print_ticket': true,
    'pos.offline_mode': true,
    'pos.price_override': true,
    'pos.void_item': true,
    'pos.void_order': true,
    'pos.delete_order': true,
    'pos.reopen_order': true,
    'pos.tax_exempt': true,
    'pos.customer_assign': true
  },
  SUPER_ADMIN: {
    POS_ACCESS: true,
    CASH_DRAWER_ACCESS: true,
    'pos.orders_view': true,
    'pos.orders_refund': true,
    'pos.discounts': true,
    'pos.gift_cards': true,
    'pos.shift_open': true,
    'pos.shift_close': true,
    'pos.split_bill': true,
    'pos.print_ticket': true,
    'pos.offline_mode': true,
    'pos.price_override': true,
    'pos.void_item': true,
    'pos.void_order': true,
    'pos.delete_order': true,
    'pos.reopen_order': true,
    'pos.tax_exempt': true,
    'pos.customer_assign': true
  },
  STORE_MANAGER: {
    POS_ACCESS: true,
    CASH_DRAWER_ACCESS: true,
    'pos.orders_view': true,
    'pos.orders_refund': true,
    'pos.discounts': true,
    'pos.gift_cards': true,
    'pos.shift_open': true,
    'pos.shift_close': true,
    'pos.split_bill': true,
    'pos.print_ticket': true,
    'pos.offline_mode': true,
    'pos.price_override': true,
    'pos.void_item': true,
    'pos.void_order': true,
    'pos.delete_order': true,
    'pos.reopen_order': true,
    'pos.tax_exempt': true,
    'pos.customer_assign': true
  },
  STORE_EMPLOYEE: {
    POS_ACCESS: true,
    CASH_DRAWER_ACCESS: true,
    'pos.orders_view': true,
    'pos.orders_refund': false,
    'pos.discounts': false,
    'pos.gift_cards': false,
    'pos.shift_open': true,
    'pos.shift_close': true,
    'pos.split_bill': true,
    'pos.print_ticket': true,
    'pos.offline_mode': true,
    'pos.price_override': false,
    'pos.void_item': true,
    'pos.void_order': false,
    'pos.delete_order': false,
    'pos.reopen_order': false,
    'pos.tax_exempt': false,
    'pos.customer_assign': true
  }
}
