import { Role } from '@prisma/client'
import { PermissionItem } from './types'

export const hrPermissions: PermissionItem[] = [
  { key: 'HR_ACCESS', name: 'Ressources Humaines (Paie)', desc: 'Consulter les salaires, éditer les fiches de paie et les contrats.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.staff_view', name: 'Voir personnel', desc: "Consulter l'annuaire des collaborateurs.", module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.staff_create', name: 'Créer collaborateur', desc: 'Enregistrer une nouvelle embauche dans le système.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.staff_edit', name: 'Modifier dossiers', desc: 'Mettre à jour les informations personnelles du personnel.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.staff_delete', name: 'Supprimer profil', desc: 'Retirer un compte collaborateur du système.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.contracts_manage', name: 'Gérer Contrats', desc: 'Éditer et clore les contrats CDI/CDD.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.evaluations_create', name: 'Évaluer personnel', desc: "Saisir les grilles d'évaluation trimestrielles.", module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.evaluations_view', name: 'Voir évaluations', desc: "Consulter l'historique d'évaluation d'un employé.", module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.leaves_approve', name: 'Valider congés', desc: 'Accepter ou refuser les congés et absences.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.leaves_create', name: 'Déclarer absence', desc: 'Enregistrer une absence maladie ou imprévue.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.attendance_view', name: 'Voir pointages', desc: 'Consulter les fiches de présences journalières.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.attendance_edit', name: 'Modifier pointages', desc: "Corriger manuellement les fiches d'heures.", module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.loans_approve', name: 'Valider prêts', desc: "Accorder ou rejeter des demandes d'acompte sur salaire.", module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.history_view', name: 'Historique RH', desc: 'Parcourir les promotions et changements de statuts.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.settings', name: 'Paramètres RH', desc: 'Définir les horaires journaliers de référence.', module: 'ressources_humaines', category: 'Configuration' }
]

export const hrDefaultPermissions: Record<Role, Record<string, boolean>> = {
  RESTAURATEUR: {
    HR_ACCESS: true,
    'hr.staff_view': true,
    'hr.staff_create': true,
    'hr.staff_edit': true,
    'hr.staff_delete': true,
    'hr.contracts_manage': true,
    'hr.evaluations_create': true,
    'hr.evaluations_view': true,
    'hr.leaves_approve': true,
    'hr.leaves_create': true,
    'hr.attendance_view': true,
    'hr.attendance_edit': true,
    'hr.loans_approve': true,
    'hr.history_view': true,
    'hr.settings': true
  },
  MANAGER: {
    HR_ACCESS: true,
    'hr.staff_view': true,
    'hr.staff_create': true,
    'hr.staff_edit': true,
    'hr.staff_delete': false,
    'hr.contracts_manage': true,
    'hr.evaluations_create': true,
    'hr.evaluations_view': true,
    'hr.leaves_approve': true,
    'hr.leaves_create': true,
    'hr.attendance_view': true,
    'hr.attendance_edit': true,
    'hr.loans_approve': true,
    'hr.history_view': true,
    'hr.settings': false
  },
  CASHIER: {
    HR_ACCESS: false,
    'hr.staff_view': false,
    'hr.staff_create': false,
    'hr.staff_edit': false,
    'hr.staff_delete': false,
    'hr.contracts_manage': false,
    'hr.evaluations_create': false,
    'hr.evaluations_view': false,
    'hr.leaves_approve': false,
    'hr.leaves_create': false,
    'hr.attendance_view': false,
    'hr.attendance_edit': false,
    'hr.loans_approve': false,
    'hr.history_view': false,
    'hr.settings': false
  },
  SERVER: {
    HR_ACCESS: false,
    'hr.staff_view': false,
    'hr.staff_create': false,
    'hr.staff_edit': false,
    'hr.staff_delete': false,
    'hr.contracts_manage': false,
    'hr.evaluations_create': false,
    'hr.evaluations_view': false,
    'hr.leaves_approve': false,
    'hr.leaves_create': false,
    'hr.attendance_view': false,
    'hr.attendance_edit': false,
    'hr.loans_approve': false,
    'hr.history_view': false,
    'hr.settings': false
  },
  KITCHEN: {
    HR_ACCESS: false,
    'hr.staff_view': false,
    'hr.staff_create': false,
    'hr.staff_edit': false,
    'hr.staff_delete': false,
    'hr.contracts_manage': false,
    'hr.evaluations_create': false,
    'hr.evaluations_view': false,
    'hr.leaves_approve': false,
    'hr.leaves_create': false,
    'hr.attendance_view': false,
    'hr.attendance_edit': false,
    'hr.loans_approve': false,
    'hr.history_view': false,
    'hr.settings': false
  },
  DELIVERY: {
    HR_ACCESS: false,
    'hr.staff_view': false,
    'hr.staff_create': false,
    'hr.staff_edit': false,
    'hr.staff_delete': false,
    'hr.contracts_manage': false,
    'hr.evaluations_create': false,
    'hr.evaluations_view': false,
    'hr.leaves_approve': false,
    'hr.leaves_create': false,
    'hr.attendance_view': false,
    'hr.attendance_edit': false,
    'hr.loans_approve': false,
    'hr.history_view': false,
    'hr.settings': false
  },
  LIVREUR: {
    HR_ACCESS: false,
    'hr.staff_view': false,
    'hr.staff_create': false,
    'hr.staff_edit': false,
    'hr.staff_delete': false,
    'hr.contracts_manage': false,
    'hr.evaluations_create': false,
    'hr.evaluations_view': false,
    'hr.leaves_approve': false,
    'hr.leaves_create': false,
    'hr.attendance_view': false,
    'hr.attendance_edit': false,
    'hr.loans_approve': false,
    'hr.history_view': false,
    'hr.settings': false
  },
  ADMIN: {
    HR_ACCESS: true,
    'hr.staff_view': true,
    'hr.staff_create': true,
    'hr.staff_edit': true,
    'hr.staff_delete': true,
    'hr.contracts_manage': true,
    'hr.evaluations_create': true,
    'hr.evaluations_view': true,
    'hr.leaves_approve': true,
    'hr.leaves_create': true,
    'hr.attendance_view': true,
    'hr.attendance_edit': true,
    'hr.loans_approve': true,
    'hr.history_view': true,
    'hr.settings': true
  },
  SUPER_ADMIN: {
    HR_ACCESS: true,
    'hr.staff_view': true,
    'hr.staff_create': true,
    'hr.staff_edit': true,
    'hr.staff_delete': true,
    'hr.contracts_manage': true,
    'hr.evaluations_create': true,
    'hr.evaluations_view': true,
    'hr.leaves_approve': true,
    'hr.leaves_create': true,
    'hr.attendance_view': true,
    'hr.attendance_edit': true,
    'hr.loans_approve': true,
    'hr.history_view': true,
    'hr.settings': true
  },
  STORE_MANAGER: {
    HR_ACCESS: true,
    'hr.staff_view': true,
    'hr.staff_create': true,
    'hr.staff_edit': true,
    'hr.staff_delete': false,
    'hr.contracts_manage': true,
    'hr.evaluations_create': true,
    'hr.evaluations_view': true,
    'hr.leaves_approve': true,
    'hr.leaves_create': true,
    'hr.attendance_view': true,
    'hr.attendance_edit': true,
    'hr.loans_approve': true,
    'hr.history_view': true,
    'hr.settings': false
  },
  STORE_EMPLOYEE: {
    HR_ACCESS: false,
    'hr.staff_view': false,
    'hr.staff_create': false,
    'hr.staff_edit': false,
    'hr.staff_delete': false,
    'hr.contracts_manage': false,
    'hr.evaluations_create': false,
    'hr.evaluations_view': false,
    'hr.leaves_approve': false,
    'hr.leaves_create': false,
    'hr.attendance_view': false,
    'hr.attendance_edit': false,
    'hr.loans_approve': false,
    'hr.history_view': false,
    'hr.settings': false
  }
}
