import { Role } from '@prisma/client'
import { PermissionItem } from './types'

export const stockPermissions: PermissionItem[] = [
  { key: 'STOCK_ACCESS', name: 'Suivi des Stocks Avancés', desc: "Enregistrer les livraisons fournisseurs, transferts d'articles, fiches de production.", module: 'stocks_inventaire', category: 'Logistique' },
  { key: 'STOCK_ADJUSTMENT', name: 'Ajustement de stock manuel', desc: 'Ajuster manuellement les quantités (perte, vol, casse, inventaire).', module: 'stocks_inventaire', category: 'Logistique' },
  { key: 'stock.supplier_create', name: 'Gérer Fournisseurs', desc: 'Ajouter et modifier les fiches de fournisseurs.', module: 'stocks_inventaire', category: 'Administration' },
  { key: 'stock.po_create', name: 'Créer Bons de commande', desc: "Rédiger des demandes d'achats de matières premières.", module: 'stocks_inventaire', category: 'Logistique' },
  { key: 'stock.po_receive', name: 'Recevoir marchandises', desc: "Valider l'entrée en stock suite à une livraison.", module: 'stocks_inventaire', category: 'Logistique' },
  { key: 'stock.transfer', name: 'Transferts inter-magasins', desc: 'Transférer des ingrédients vers un autre magasin du groupe.', module: 'stocks_inventaire', category: 'Logistique' },
  { key: 'stock.valuation', name: 'Valorisation stock', desc: 'Consulter la valeur financière totale du stock.', module: 'stocks_inventaire', category: 'Lecture' },
  { key: 'stock.alerts_config', name: 'Alerte stock bas', desc: 'Définir des seuils de réapprovisionnement automatique.', module: 'stocks_inventaire', category: 'Configuration' },
  { key: 'stock.recipe_edit', name: 'Fiche Recette / Plats', desc: 'Modifier les ingrédients constituant un plat.', module: 'stocks_inventaire', category: 'Administration' },
  { key: 'stock.inventory_count', name: 'Inventaire physique', desc: 'Effectuer un inventaire physique de fin de mois.', module: 'stocks_inventaire', category: 'Logistique' },
  { key: 'stock.supplier_payout', name: 'Paiements fournisseurs', desc: 'Valider et tracer les paiements de factures achats.', module: 'stocks_inventaire', category: 'Logistique' },
  { key: 'stock.waste_report', name: 'Rapport des pertes', desc: 'Enregistrer la casse et les invendus périmés.', module: 'stocks_inventaire', category: 'Logistique' }
]

export const stockDefaultPermissions: Record<Role, Record<string, boolean>> = {
  RESTAURATEUR: {
    STOCK_ACCESS: true,
    STOCK_ADJUSTMENT: true,
    'stock.supplier_create': true,
    'stock.po_create': true,
    'stock.po_receive': true,
    'stock.transfer': true,
    'stock.valuation': true,
    'stock.alerts_config': true,
    'stock.recipe_edit': true,
    'stock.inventory_count': true,
    'stock.supplier_payout': true,
    'stock.waste_report': true
  },
  MANAGER: {
    STOCK_ACCESS: true,
    STOCK_ADJUSTMENT: true,
    'stock.supplier_create': true,
    'stock.po_create': true,
    'stock.po_receive': true,
    'stock.transfer': true,
    'stock.valuation': true,
    'stock.alerts_config': true,
    'stock.recipe_edit': true,
    'stock.inventory_count': true,
    'stock.supplier_payout': true,
    'stock.waste_report': true
  },
  CASHIER: {
    STOCK_ACCESS: false,
    STOCK_ADJUSTMENT: false,
    'stock.supplier_create': false,
    'stock.po_create': false,
    'stock.po_receive': false,
    'stock.transfer': false,
    'stock.valuation': false,
    'stock.alerts_config': false,
    'stock.recipe_edit': false,
    'stock.inventory_count': false,
    'stock.supplier_payout': false,
    'stock.waste_report': false
  },
  SERVER: {
    STOCK_ACCESS: false,
    STOCK_ADJUSTMENT: false,
    'stock.supplier_create': false,
    'stock.po_create': false,
    'stock.po_receive': false,
    'stock.transfer': false,
    'stock.valuation': false,
    'stock.alerts_config': false,
    'stock.recipe_edit': false,
    'stock.inventory_count': false,
    'stock.supplier_payout': false,
    'stock.waste_report': false
  },
  KITCHEN: {
    STOCK_ACCESS: false,
    STOCK_ADJUSTMENT: false,
    'stock.supplier_create': false,
    'stock.po_create': false,
    'stock.po_receive': false,
    'stock.transfer': false,
    'stock.valuation': false,
    'stock.alerts_config': false,
    'stock.recipe_edit': false,
    'stock.inventory_count': false,
    'stock.supplier_payout': false,
    'stock.waste_report': false
  },
  DELIVERY: {
    STOCK_ACCESS: false,
    STOCK_ADJUSTMENT: false,
    'stock.supplier_create': false,
    'stock.po_create': false,
    'stock.po_receive': false,
    'stock.transfer': false,
    'stock.valuation': false,
    'stock.alerts_config': false,
    'stock.recipe_edit': false,
    'stock.inventory_count': false,
    'stock.supplier_payout': false,
    'stock.waste_report': false
  },
  LIVREUR: {
    STOCK_ACCESS: false,
    STOCK_ADJUSTMENT: false,
    'stock.supplier_create': false,
    'stock.po_create': false,
    'stock.po_receive': false,
    'stock.transfer': false,
    'stock.valuation': false,
    'stock.alerts_config': false,
    'stock.recipe_edit': false,
    'stock.inventory_count': false,
    'stock.supplier_payout': false,
    'stock.waste_report': false
  },
  ADMIN: {
    STOCK_ACCESS: true,
    STOCK_ADJUSTMENT: true,
    'stock.supplier_create': true,
    'stock.po_create': true,
    'stock.po_receive': true,
    'stock.transfer': true,
    'stock.valuation': true,
    'stock.alerts_config': true,
    'stock.recipe_edit': true,
    'stock.inventory_count': true,
    'stock.supplier_payout': true,
    'stock.waste_report': true
  },
  SUPER_ADMIN: {
    STOCK_ACCESS: true,
    STOCK_ADJUSTMENT: true,
    'stock.supplier_create': true,
    'stock.po_create': true,
    'stock.po_receive': true,
    'stock.transfer': true,
    'stock.valuation': true,
    'stock.alerts_config': true,
    'stock.recipe_edit': true,
    'stock.inventory_count': true,
    'stock.supplier_payout': true,
    'stock.waste_report': true
  },
  STORE_MANAGER: {
    STOCK_ACCESS: true,
    STOCK_ADJUSTMENT: true,
    'stock.supplier_create': true,
    'stock.po_create': true,
    'stock.po_receive': true,
    'stock.transfer': true,
    'stock.valuation': true,
    'stock.alerts_config': true,
    'stock.recipe_edit': true,
    'stock.inventory_count': true,
    'stock.supplier_payout': true,
    'stock.waste_report': true
  },
  STORE_EMPLOYEE: {
    STOCK_ACCESS: false,
    STOCK_ADJUSTMENT: false,
    'stock.supplier_create': false,
    'stock.po_create': false,
    'stock.po_receive': false,
    'stock.transfer': false,
    'stock.valuation': false,
    'stock.alerts_config': false,
    'stock.recipe_edit': false,
    'stock.inventory_count': false,
    'stock.supplier_payout': false,
    'stock.waste_report': false
  }
}
