apiVersion: v1
kind: Service
metadata:
  name: pos-app-service
  namespace: pos-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: pos-app
