apiVersion: v1
kind: Secret
metadata:
  name: pos-app-env
  namespace: pos-app
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:password@pos-postgres:5432/pos_restaurant?schema=public"
  DIRECT_DATABASE_URL: "postgresql://postgres:password@pos-postgres:5432/pos_restaurant?schema=public"
  REDIS_URL: "redis://pos-redis:6379"
  NEXTAUTH_SECRET: "CHANGE_ME_RANDOM_BASE64"
  NEXTAUTH_URL: "https://example.com"
  POSTGRES_PASSWORD: "password"
  PRISMA_ENABLE_DB_PUSH_FALLBACK: "false"
  PRISMA_SEED_ON_START: "false"
