import { Role } from '@prisma/client'

export interface PermissionItem {
  key: string
  name: string
  desc: string
  module: string
  category: string
}

export interface ModuleInfo {
  id: string
  name: string
  desc: string
  pages: { name: string; path: string }[]
}

export const MODULES_LIST: ModuleInfo[] = [
  {
    id: 'tableau_de_bord',
    name: 'Tableau de Bord',
    desc: "Suivi des performances, indicateurs clés de vente et rapports d'activité transversaux.",
    pages: [
      { name: 'Dashboard global', path: '/restaurateur/dashboard' },
      { name: 'Rapports avancés', path: '/restaurateur/analytics' }
    ]
  },
  {
    id: 'commercial_pos',
    name: 'Commercial & POS',
    desc: 'Opérations de caisse physiques, prise de commande sur place et gestion du tiroir-caisse.',
    pages: [
      { name: 'Interface Point de Vente (POS)', path: '/cashier' },
      { name: 'Sessions de caisse', path: '/cashier/shifts' }
    ]
  },
  {
    id: 'cuisine_kds',
    name: 'Cuisine (KDS)',
    desc: 'Affichage en cuisine et gestion du flux de préparation des plats en temps réel.',
    pages: [
      { name: 'Écran Cuisine (KDS)', path: '/kitchen' }
    ]
  },
  {
    id: 'stocks_inventaire',
    name: 'Achats & Stocks',
    desc: 'Suivi des stocks d\'ingrédients et produits, commandes fournisseurs et inventaires.',
    pages: [
      { name: 'Fiche Article & Stock', path: '/restaurateur/stock' },
      { name: 'Commandes Fournisseurs', path: '/restaurateur/stock/orders' },
      { name: 'Mouvements de stock', path: '/restaurateur/stock/movements' }
    ]
  },
  {
    id: 'ressources_humaines',
    name: 'Ressources Humaines',
    desc: 'Dossiers du personnel, fiches de présence, contrats de travail et évaluations.',
    pages: [
      { name: 'Gestion du Personnel', path: '/restaurateur/staff' },
      { name: 'Fiches de Présence', path: '/restaurateur/staff/presences' },
      { name: 'Évaluations', path: '/restaurateur/staff/evaluations' }
    ]
  },
  {
    id: 'comptabilite_paie',
    name: 'Comptabilité & Paie',
    desc: 'Bulletins de paie mensuels des collaborateurs et clôtures comptables de périodes.',
    pages: [
      { name: 'Gestion de la Paie', path: '/restaurateur/payroll' },
      { name: 'Clôtures de mois', path: '/restaurateur/payroll/closures' }
    ]
  },
  {
    id: 'livraison',
    name: 'Gestion des Livraisons',
    desc: 'Prise en charge des livraisons, affectation des livreurs et suivi GPS en direct.',
    pages: [
      { name: 'Suivi des Livraisons', path: '/restaurateur/delivery' }
    ]
  },
  {
    id: 'fidelisation_clients',
    name: 'Fidélisation & CRM',
    desc: 'Gestion des profils clients, fidélisation, cumul de points et codes promotions.',
    pages: [
      { name: 'Fiche Clients & Fidélité', path: '/restaurateur/clients' }
    ]
  },
  {
    id: 'reservations_salles',
    name: 'Réservations & Tables',
    desc: 'Gestion des réservations de tables et plan de salle interactif de l\'établissement.',
    pages: [
      { name: 'Agenda des Réservations', path: '/restaurateur/bookings' },
      { name: 'Plan de salle', path: '/restaurateur/tables' }
    ]
  },
  {
    id: 'ecommerce_web',
    name: 'E-commerce & Web',
    desc: 'Gestion de la commande en ligne e-commerce, catalogue public et paiements Stripe/OM/MTN.',
    pages: [
      { name: 'Catalogue Public Web', path: '/restaurateur/ecommerce' },
      { name: 'Commandes en ligne', path: '/restaurateur/ecommerce/orders' }
    ]
  },
  {
    id: 'configuration_systeme',
    name: 'Configuration & API',
    desc: 'Paramétrage des adresses IP des imprimantes, jetons d\'API et webhooks globaux.',
    pages: [
      { name: 'Paramètres généraux', path: '/restaurateur/settings' },
      { name: 'Imprimantes réseau', path: '/restaurateur/settings/printers' },
      { name: 'Intégrations & API', path: '/restaurateur/settings/api' }
    ]
  }
]

export const PERMISSIONS_LIST: PermissionItem[] = [
  // 1. Tableau de Bord
  { key: 'dashboard.view', name: 'Accès au Dashboard', desc: 'Consulter le tableau de bord principal.', module: 'tableau_de_bord', category: 'Lecture' },
  { key: 'dashboard.read_analytics', name: 'Statistiques & KPIs', desc: 'Visualiser les chiffres clés et courbes d\'activité.', module: 'tableau_de_bord', category: 'Lecture' },
  { key: 'ANALYTICS_ACCESS', name: 'Rapports & Stats de performance', desc: 'Accéder aux graphiques de ventes journalières et évaluations de marge.', module: 'tableau_de_bord', category: 'Lecture' },
  { key: 'dashboard.margins', name: 'Consulter les marges', desc: 'Afficher les marges par produit et taux de rentabilité.', module: 'tableau_de_bord', category: 'Lecture' },
  { key: 'dashboard.compare', name: 'Comparaison de périodes', desc: 'Comparer les ventes d\'un mois sur l\'autre.', module: 'tableau_de_bord', category: 'Lecture' },
  { key: 'dashboard.export_pdf', name: 'Exporter en PDF', desc: 'Générer des rapports au format PDF professionnel.', module: 'tableau_de_bord', category: 'Actions' },
  { key: 'dashboard.export_excel', name: 'Exporter en Excel', desc: 'Exporter des rapports multi-onglets au format Excel.', module: 'tableau_de_bord', category: 'Actions' },

  // 2. Commercial & POS
  { key: 'POS_ACCESS', name: 'Point de Vente (POS)', desc: 'Prendre des commandes, encaisser les paiements, gérer le panier local.', module: 'commercial_pos', category: 'Opérations' },
  { key: 'CASH_DRAWER_ACCESS', name: 'Tiroir-caisse physique', desc: 'Ouvrir le tiroir-caisse manuellement et voir le montant attendu en caisse.', module: 'commercial_pos', category: 'Opérations' },
  { key: 'pos.orders_view', name: 'Historique des Commandes', desc: 'Consulter toutes les commandes enregistrées dans l\'établissement.', module: 'commercial_pos', category: 'Opérations' },
  { key: 'pos.orders_refund', name: 'Remboursements', desc: 'Annuler des commandes et gérer les retours d\'argent.', module: 'commercial_pos', category: 'Actions' },
  { key: 'pos.discounts', name: 'Appliquer des remises', desc: 'Faire des rabais en pourcentage ou montant fixe.', module: 'commercial_pos', category: 'Actions' },
  { key: 'pos.gift_cards', name: 'Cartes cadeaux', desc: 'Émettre et encaisser par cartes cadeaux.', module: 'commercial_pos', category: 'Opérations' },
  { key: 'pos.shift_open', name: 'Ouvrir session caisse', desc: 'Déclarer le fond de caisse initial le matin.', module: 'commercial_pos', category: 'Opérations' },
  { key: 'pos.shift_close', name: 'Clôturer session caisse', desc: 'Compter et valider la caisse en fin de journée.', module: 'commercial_pos', category: 'Opérations' },
  { key: 'pos.split_bill', name: 'Diviser l\'addition', desc: 'Séparer les tickets de caisse par client.', module: 'commercial_pos', category: 'Actions' },
  { key: 'pos.print_ticket', name: 'Réimprimer ticket', desc: 'Sortir un duplicata du reçu client.', module: 'commercial_pos', category: 'Actions' },
  { key: 'pos.offline_mode', name: 'Mode hors-ligne', desc: 'Vendre sur le POS sans connexion internet active.', module: 'commercial_pos', category: 'Système' },
  { key: 'pos.price_override', name: 'Surcharger prix', desc: 'Modifier le prix de vente d\'un plat directement au POS.', module: 'commercial_pos', category: 'Actions' },
  { key: 'pos.void_item', name: 'Supprimer article panier', desc: 'Retirer un article d\'un ticket de caisse en cours de saisie.', module: 'commercial_pos', category: 'Actions' },
  { key: 'pos.tax_exempt', name: 'Exemptions de taxe', desc: 'Appliquer un profil de commande exempté de TVA.', module: 'commercial_pos', category: 'Actions' },
  { key: 'pos.customer_assign', name: 'Associer client', desc: 'Lier une fiche client à une commande POS.', module: 'commercial_pos', category: 'Opérations' },

  // 3. Cuisine (KDS)
  { key: 'KDS_ACCESS', name: 'Kitchen Display System (KDS)', desc: 'Consulter et valider les commandes en préparation en cuisine.', module: 'cuisine_kds', category: 'Préparation' },
  { key: 'kds.orders_view', name: 'Commandes en Cuisine', desc: 'Visualiser les tickets de cuisine actifs.', module: 'cuisine_kds', category: 'Préparation' },
  { key: 'kds.status_update', name: 'Valider préparation', desc: 'Marquer les plats comme "Prêt".', module: 'cuisine_kds', category: 'Préparation' },
  { key: 'kds.alert_send', name: 'Envoyer alertes', desc: 'Notifier les serveurs par voyant ou signal sonore.', module: 'cuisine_kds', category: 'Préparation' },
  { key: 'kds.history', name: 'Historique Cuisine', desc: 'Consulter le journal de traitement des plats.', module: 'cuisine_kds', category: 'Préparation' },

  // 4. Stocks & Inventaire
  { key: 'STOCK_ACCESS', name: 'Suivi des Stocks Avancés', desc: 'Enregistrer les livraisons fournisseurs, transferts d\'articles, fiches de production.', module: 'stocks_inventaire', category: 'Logistique' },
  { key: 'STOCK_ADJUSTMENT', name: 'Ajustement de stock manuel', desc: 'Ajuster manuellement les quantités (perte, vol, casse, inventaire).', module: 'stocks_inventaire', category: 'Logistique' },
  { key: 'stock.supplier_create', name: 'Gérer Fournisseurs', desc: 'Ajouter et modifier les fiches de fournisseurs.', module: 'stocks_inventaire', category: 'Administration' },
  { key: 'stock.po_create', name: 'Créer Bons de commande', desc: 'Rédiger des demandes d\'achats de matières premières.', module: 'stocks_inventaire', category: 'Logistique' },
  { key: 'stock.po_receive', name: 'Recevoir marchandises', desc: 'Valider l\'entrée en stock suite à une livraison.', module: 'stocks_inventaire', category: 'Logistique' },
  { key: 'stock.transfer', name: 'Transferts inter-magasins', desc: 'Transférer des ingrédients vers un autre magasin du groupe.', module: 'stocks_inventaire', category: 'Logistique' },
  { key: 'stock.valuation', name: 'Valorisation stock', desc: 'Consulter la valeur financière totale du stock.', module: 'stocks_inventaire', category: 'Lecture' },
  { key: 'stock.alerts_config', name: 'Alerte stock bas', desc: 'Définir des seuils de réapprovisionnement automatique.', module: 'stocks_inventaire', category: 'Configuration' },
  { key: 'stock.recipe_edit', name: 'Fiche Recette / Plats', desc: 'Modifier les ingrédients constituant un plat.', module: 'stocks_inventaire', category: 'Administration' },
  { key: 'stock.inventory_count', name: 'Inventaire physique', desc: 'Effectuer un inventaire physique de fin de mois.', module: 'stocks_inventaire', category: 'Logistique' },
  { key: 'stock.supplier_payout', name: 'Paiements fournisseurs', desc: 'Valider et tracer les paiements de factures achats.', module: 'stocks_inventaire', category: 'Logistique' },
  { key: 'stock.waste_report', name: 'Rapport des pertes', desc: 'Enregistrer la casse et les invendus périmés.', module: 'stocks_inventaire', category: 'Logistique' },

  // 5. Ressources Humaines
  { key: 'HR_ACCESS', name: 'Ressources Humaines (Paie)', desc: 'Consulter les salaires, éditer les fiches de paie et les contrats.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.staff_view', name: 'Voir personnel', desc: 'Consulter l\'annuaire des collaborateurs.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.staff_create', name: 'Créer collaborateur', desc: 'Enregistrer une nouvelle embauche dans le système.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.staff_edit', name: 'Modifier dossiers', desc: 'Mettre à jour les informations personnelles du personnel.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.staff_delete', name: 'Supprimer profil', desc: 'Retirer un compte collaborateur du système.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.contracts_manage', name: 'Gérer Contrats', desc: 'Éditer et clore les contrats CDI/CDD.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.evaluations_create', name: 'Évaluer personnel', desc: 'Saisir les grilles d\'évaluation trimestrielles.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.evaluations_view', name: 'Voir évaluations', desc: 'Consulter l\'historique d\'évaluation d\'un employé.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.leaves_approve', name: 'Valider congés', desc: 'Accepter ou refuser les congés et absences.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.leaves_create', name: 'Déclarer absence', desc: 'Enregistrer une absence maladie ou imprévue.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.attendance_view', name: 'Voir pointages', desc: 'Consulter les fiches de présences journalières.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.attendance_edit', name: 'Modifier pointages', desc: 'Corriger manuellement les fiches d\'heures.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.loans_approve', name: 'Valider prêts', desc: 'Accorder ou rejeter des demandes d\'acompte sur salaire.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.history_view', name: 'Historique RH', desc: 'Parcourir les promotions et changements de statuts.', module: 'ressources_humaines', category: 'RH' },
  { key: 'hr.settings', name: 'Paramètres RH', desc: 'Définir les horaires journaliers de référence.', module: 'ressources_humaines', category: 'Configuration' },

  // 6. Comptabilité & Paie
  { key: 'accounting.payroll_generate', name: 'Générer bulletins', desc: 'Calculer la paie mensuelle et appliquer les taxes CNPS/ITS.', module: 'comptabilite_paie', category: 'Comptabilité' },
  { key: 'accounting.payroll_pay', name: 'Payer salaires', desc: 'Émettre les ordres de paiement des salaires.', module: 'comptabilite_paie', category: 'Comptabilité' },
  { key: 'accounting.payroll_view', name: 'Consulter bulletins', desc: 'Accéder aux archives des bulletins de paie édités.', module: 'comptabilite_paie', category: 'Comptabilité' },
  { key: 'accounting.closures_view', name: 'Voir clôtures', desc: 'Consulter les clôtures mensuelles archivées.', module: 'comptabilite_paie', category: 'Comptabilité' },
  { key: 'accounting.closures_create', name: 'Clôturer période', desc: 'Figer les comptes d\'un mois de paie écoulé.', module: 'comptabilite_paie', category: 'Comptabilité' },
  { key: 'accounting.payouts_manage', name: 'Demande décaissement', desc: 'Tracer les retraits de caisse pour frais exceptionnels.', module: 'comptabilite_paie', category: 'Comptabilité' },
  { key: 'accounting.taxes_export', name: 'Déclaration fiscale', desc: 'Exporter les états fiscaux CNPS, IGR et CN.', module: 'comptabilite_paie', category: 'Actions' },
  { key: 'accounting.sales_journal', name: 'Journal de ventes', desc: 'Consulter le récapitulatif des recettes par compte comptable.', module: 'comptabilite_paie', category: 'Lecture' },
  { key: 'accounting.expenses_create', name: 'Déclarer charge', desc: 'Saisir les factures d\'eau, électricité, loyer.', module: 'comptabilite_paie', category: 'Comptabilité' },
  { key: 'accounting.bank_reconciliation', name: 'Rapprochement bancaire', desc: 'Valider la concordance des extraits de banque.', module: 'comptabilite_paie', category: 'Comptabilité' },

  // 7. Livraisons
  { key: 'delivery.orders_view', name: 'Voir livraisons', desc: 'Lister les commandes affectées à la livraison à domicile.', module: 'livraison', category: 'Livraison' },
  { key: 'delivery.driver_assign', name: 'Assigner livreur', desc: 'Attribuer manuellement une course à un livreur disponible.', module: 'livraison', category: 'Actions' },
  { key: 'delivery.gps_tracking', name: 'Suivi GPS', desc: 'Visualiser la position du coursier sur la carte.', module: 'livraison', category: 'Lecture' },
  { key: 'delivery.pwa_access', name: 'Accès livreur PWA', desc: 'Se connecter à l\'espace mobile de livraison.', module: 'livraison', category: 'Système' },
  { key: 'delivery.settings', name: 'Frais de livraison', desc: 'Définir les frais de port et périmètres de livraison.', module: 'livraison', category: 'Configuration' },
  { key: 'delivery.driver_payout', name: 'Commissions coursiers', desc: 'Calculer les indemnités de trajet des livreurs.', module: 'livraison', category: 'Comptabilité' },
  { key: 'delivery.status_override', name: 'Forcer statuts', desc: 'Modifier manuellement le statut de livraison d\'une commande.', module: 'livraison', category: 'Actions' },
  { key: 'delivery.route_optimization', name: 'Optimiser trajets', desc: 'Calculer l\'ordre de passage optimal des adresses.', module: 'livraison', category: 'Actions' },

  // 8. Fidélisation & CRM
  { key: 'loyalty.customers_view', name: 'Voir clients', desc: 'Rechercher un client dans le fichier CRM.', module: 'fidelisation_clients', category: 'Fidélisation' },
  { key: 'loyalty.customers_edit', name: 'Modifier clients', desc: 'Changer les adresses, e-mails ou notes clients.', module: 'fidelisation_clients', category: 'Fidélisation' },
  { key: 'loyalty.points_add', name: 'Créditer points', desc: 'Ajouter manuellement des points de fidélité.', module: 'fidelisation_clients', category: 'Actions' },
  { key: 'loyalty.points_reset', name: 'Remise à zéro', desc: 'Réinitialiser les compteurs de points fidélité.', module: 'fidelisation_clients', category: 'Actions' },
  { key: 'loyalty.rewards_manage', name: 'Gérer récompenses', desc: 'Créer les paliers de cadeaux fidélité.', module: 'fidelisation_clients', category: 'Fidélisation' },
  { key: 'loyalty.promotions_manage', name: 'Gérer promotions', desc: 'Créer des codes de réductions temporaires.', module: 'fidelisation_clients', category: 'Fidélisation' },
  { key: 'loyalty.export', name: 'Exporter CRM', desc: 'Télécharger le fichier de contacts clients.', module: 'fidelisation_clients', category: 'Actions' },

  // 9. Réservations & Tables
  { key: 'booking.view', name: 'Voir réservations', desc: 'Visualiser l\'agenda et les réservations du jour.', module: 'reservations_salles', category: 'Salle' },
  { key: 'booking.create', name: 'Créer réservation', desc: 'Enregistrer une table réservée par téléphone ou en ligne.', module: 'reservations_salles', category: 'Salle' },
  { key: 'booking.tables_manage', name: 'Plan de table', desc: 'Modifier l\'implantation des tables en salle.', module: 'reservations_salles', category: 'Salle' },
  { key: 'booking.settings', name: 'Paramètres réservations', desc: 'Définir les plages horaires et la capacité d\'accueil.', module: 'reservations_salles', category: 'Configuration' },
  { key: 'booking.cancel', name: 'Annuler réservation', desc: 'Annuler une réservation avec motif.', module: 'reservations_salles', category: 'Actions' },
  { key: 'booking.check_in', name: 'Installer clients', desc: 'Marquer une table comme "Occupée" à l\'arrivée.', module: 'reservations_salles', category: 'Salle' },
  { key: 'booking.notifications', name: 'Rappels automatiques', desc: 'Déclencher l\'envoi de SMS de confirmation de table.', module: 'reservations_salles', category: 'Actions' },
  { key: 'booking.history', name: 'Statistiques d\'occupation', desc: 'Consulter le taux de remplissage des tables.', module: 'reservations_salles', category: 'Lecture' },

  // 10. E-commerce & Web
  { key: 'ecommerce.catalog_sync', name: 'Synchroniser Menu', desc: 'Publier les articles POS sur le site web public.', module: 'ecommerce_web', category: 'Web' },
  { key: 'ecommerce.orders_view', name: 'Voir commandes web', desc: 'Consulter le panier en ligne et les commandes reçues.', module: 'ecommerce_web', category: 'Web' },
  { key: 'ecommerce.orders_accept', name: 'Accepter commandes', desc: 'Envoyer les paniers en ligne vers le flux POS/KDS.', module: 'ecommerce_web', category: 'Actions' },
  { key: 'ecommerce.settings', name: 'Passerelles de paiement', desc: 'Configurer les comptes Stripe et Mobile Money.', module: 'ecommerce_web', category: 'Configuration' },
  { key: 'ecommerce.delivery_fees', name: 'Frais de livraison web', desc: 'Configurer les grilles de prix e-commerce.', module: 'ecommerce_web', category: 'Configuration' },
  { key: 'ecommerce.analytics', name: 'KPIs E-commerce', desc: 'Suivre le taux de rebond et chiffre d\'affaires en ligne.', module: 'ecommerce_web', category: 'Lecture' },

  // 11. Configuration & API
  { key: 'CONFIG_ACCESS', name: 'Configuration Système & Imprimantes', desc: 'Modifier les adresses IP des imprimantes locales, jetons d\'API et webhook.', module: 'configuration_systeme', category: 'Système' },
  { key: 'admin.users_manage', name: 'Gérer utilisateurs', desc: 'Créer, éditer ou suspendre des comptes de connexion.', module: 'configuration_systeme', category: 'Administration' },
  { key: 'admin.roles_permissions', name: 'Gérer permissions', desc: 'Changer les permissions par défaut liées aux rôles.', module: 'configuration_systeme', category: 'Administration' },
  { key: 'admin.store_edit', name: 'Fiche Établissement', desc: 'Mettre à jour le SIRET, téléphone et logo du restaurant.', module: 'configuration_systeme', category: 'Administration' },
  { key: 'admin.api_tokens', name: 'Jetons d\'API', desc: 'Générer des clés secrètes pour intégrations tierces.', module: 'configuration_systeme', category: 'Système' },
  { key: 'admin.printers_manage', name: 'Configurer imprimantes', desc: 'Déclarer les imprimantes de tickets thermiques.', module: 'configuration_systeme', category: 'Système' },
  { key: 'admin.rounding_rules', name: 'Arrondis monétaires', desc: 'Configurer l\'arrondi de caisse pour le rendu de monnaie.', module: 'configuration_systeme', category: 'Configuration' },
  { key: 'admin.security_settings', name: 'Double facteur (2FA)', desc: 'Activer l\'authentification renforcée obligatoire.', module: 'configuration_systeme', category: 'Configuration' },
  { key: 'admin.audit_logs', name: 'Journaux d\'audit', desc: 'Consulter l\'historique des connexions et actions critiques.', module: 'configuration_systeme', category: 'Lecture' },
  { key: 'admin.db_backup', name: 'Sauvegarder base', desc: 'Lancer un export SQL de sécurité de la base.', module: 'configuration_systeme', category: 'Actions' }
]

export const DEFAULT_PERMISSIONS: Record<Role, Record<string, boolean>> = {
  RESTAURATEUR: {
    POS_ACCESS: true,
    CASH_DRAWER_ACCESS: true,
    KDS_ACCESS: true,
    STOCK_ACCESS: true,
    STOCK_ADJUSTMENT: true,
    HR_ACCESS: true,
    ANALYTICS_ACCESS: true,
    CONFIG_ACCESS: true,
    // defaults for new keys
    'dashboard.view': true,
    'dashboard.read_analytics': true,
    'dashboard.margins': true,
    'dashboard.compare': true,
    'dashboard.export_pdf': true,
    'dashboard.export_excel': true,
    'pos.orders_view': true,
    'pos.orders_refund': true,
    'pos.discounts': true,
    'pos.gift_cards': true,
    'pos.shift_open': true,
    'pos.shift_close': true,
    'pos.split_bill': true,
    'pos.print_ticket': true,
    'pos.offline_mode': true,
    'pos.price_override': true,
    'pos.void_item': true,
    'pos.tax_exempt': true,
    'pos.customer_assign': true,
    'kds.orders_view': true,
    'kds.status_update': true,
    'kds.alert_send': true,
    'kds.history': true,
    'stock.supplier_create': true,
    'stock.po_create': true,
    'stock.po_receive': true,
    'stock.transfer': true,
    'stock.valuation': true,
    'stock.alerts_config': true,
    'stock.recipe_edit': true,
    'stock.inventory_count': true,
    'stock.supplier_payout': true,
    'stock.waste_report': true,
    'hr.staff_view': true,
    'hr.staff_create': true,
    'hr.staff_edit': true,
    'hr.staff_delete': true,
    'hr.contracts_manage': true,
    'hr.evaluations_create': true,
    'hr.evaluations_view': true,
    'hr.leaves_approve': true,
    'hr.leaves_create': true,
    'hr.attendance_view': true,
    'hr.attendance_edit': true,
    'hr.loans_approve': true,
    'hr.history_view': true,
    'hr.settings': true,
    'accounting.payroll_generate': true,
    'accounting.payroll_pay': true,
    'accounting.payroll_view': true,
    'accounting.closures_view': true,
    'accounting.closures_create': true,
    'accounting.payouts_manage': true,
    'accounting.taxes_export': true,
    'accounting.sales_journal': true,
    'accounting.expenses_create': true,
    'accounting.bank_reconciliation': true,
    'delivery.orders_view': true,
    'delivery.driver_assign': true,
    'delivery.gps_tracking': true,
    'delivery.pwa_access': true,
    'delivery.settings': true,
    'delivery.driver_payout': true,
    'delivery.status_override': true,
    'delivery.route_optimization': true,
    'loyalty.customers_view': true,
    'loyalty.customers_edit': true,
    'loyalty.points_add': true,
    'loyalty.points_reset': true,
    'loyalty.rewards_manage': true,
    'loyalty.promotions_manage': true,
    'loyalty.export': true,
    'booking.view': true,
    'booking.create': true,
    'booking.tables_manage': true,
    'booking.settings': true,
    'booking.cancel': true,
    'booking.check_in': true,
    'booking.notifications': true,
    'booking.history': true,
    'ecommerce.catalog_sync': true,
    'ecommerce.orders_view': true,
    'ecommerce.orders_accept': true,
    'ecommerce.settings': true,
    'ecommerce.delivery_fees': true,
    'ecommerce.analytics': true,
    'admin.users_manage': true,
    'admin.roles_permissions': true,
    'admin.store_edit': true,
    'admin.api_tokens': true,
    'admin.printers_manage': true,
    'admin.rounding_rules': true,
    'admin.security_settings': true,
    'admin.audit_logs': true,
    'admin.db_backup': true
  },
  MANAGER: {
    POS_ACCESS: true,
    CASH_DRAWER_ACCESS: true,
    KDS_ACCESS: true,
    STOCK_ACCESS: true,
    STOCK_ADJUSTMENT: true,
    HR_ACCESS: true,
    ANALYTICS_ACCESS: true,
    CONFIG_ACCESS: false,
    'dashboard.view': true,
    'dashboard.read_analytics': true,
    'dashboard.margins': true,
    'dashboard.compare': true,
    'dashboard.export_pdf': true,
    'dashboard.export_excel': true,
    'pos.orders_view': true,
    'pos.orders_refund': true,
    'pos.discounts': true,
    'pos.gift_cards': true,
    'pos.shift_open': true,
    'pos.shift_close': true,
    'pos.split_bill': true,
    'pos.print_ticket': true,
    'pos.offline_mode': true,
    'pos.price_override': true,
    'pos.void_item': true,
    'pos.tax_exempt': true,
    'pos.customer_assign': true,
    'kds.orders_view': true,
    'kds.status_update': true,
    'kds.alert_send': true,
    'kds.history': true,
    'stock.supplier_create': true,
    'stock.po_create': true,
    'stock.po_receive': true,
    'stock.transfer': true,
    'stock.valuation': true,
    'stock.alerts_config': true,
    'stock.recipe_edit': true,
    'stock.inventory_count': true,
    'stock.supplier_payout': true,
    'stock.waste_report': true,
    'hr.staff_view': true,
    'hr.staff_create': true,
    'hr.staff_edit': true,
    'hr.staff_delete': false,
    'hr.contracts_manage': true,
    'hr.evaluations_create': true,
    'hr.evaluations_view': true,
    'hr.leaves_approve': true,
    'hr.leaves_create': true,
    'hr.attendance_view': true,
    'hr.attendance_edit': true,
    'hr.loans_approve': true,
    'hr.history_view': true,
    'hr.settings': false,
    'accounting.payroll_generate': false,
    'accounting.payroll_pay': false,
    'accounting.payroll_view': true,
    'accounting.closures_view': true,
    'accounting.closures_create': false,
    'accounting.payouts_manage': true,
    'accounting.taxes_export': false,
    'accounting.sales_journal': true,
    'accounting.expenses_create': true,
    'accounting.bank_reconciliation': false,
    'delivery.orders_view': true,
    'delivery.driver_assign': true,
    'delivery.gps_tracking': true,
    'delivery.pwa_access': true,
    'delivery.settings': false,
    'delivery.driver_payout': true,
    'delivery.status_override': true,
    'delivery.route_optimization': true,
    'loyalty.customers_view': true,
    'loyalty.customers_edit': true,
    'loyalty.points_add': true,
    'loyalty.points_reset': false,
    'loyalty.rewards_manage': true,
    'loyalty.promotions_manage': true,
    'loyalty.export': true,
    'booking.view': true,
    'booking.create': true,
    'booking.tables_manage': true,
    'booking.settings': true,
    'booking.cancel': true,
    'booking.check_in': true,
    'booking.notifications': true,
    'booking.history': true,
    'ecommerce.catalog_sync': true,
    'ecommerce.orders_view': true,
    'ecommerce.orders_accept': true,
    'ecommerce.settings': false,
    'ecommerce.delivery_fees': false,
    'ecommerce.analytics': true,
    'admin.users_manage': false,
    'admin.roles_permissions': false,
    'admin.store_edit': false,
    'admin.api_tokens': false,
    'admin.printers_manage': true,
    'admin.rounding_rules': false,
    'admin.security_settings': false,
    'admin.audit_logs': true,
    'admin.db_backup': false
  },
  CASHIER: {
    POS_ACCESS: true,
    CASH_DRAWER_ACCESS: true,
    KDS_ACCESS: false,
    STOCK_ACCESS: false,
    STOCK_ADJUSTMENT: false,
    HR_ACCESS: false,
    ANALYTICS_ACCESS: false,
    CONFIG_ACCESS: false,
    'dashboard.view': false,
    'dashboard.read_analytics': false,
    'dashboard.margins': false,
    'dashboard.compare': false,
    'dashboard.export_pdf': false,
    'dashboard.export_excel': false,
    'pos.orders_view': true,
    'pos.orders_refund': false,
    'pos.discounts': false,
    'pos.gift_cards': true,
    'pos.shift_open': true,
    'pos.shift_close': true,
    'pos.split_bill': true,
    'pos.print_ticket': true,
    'pos.offline_mode': true,
    'pos.price_override': false,
    'pos.void_item': true,
    'pos.tax_exempt': false,
    'pos.customer_assign': true,
    'kds.orders_view': false,
    'kds.status_update': false,
    'kds.alert_send': false,
    'kds.history': false,
    'stock.supplier_create': false,
    'stock.po_create': false,
    'stock.po_receive': false,
    'stock.transfer': false,
    'stock.valuation': false,
    'stock.alerts_config': false,
    'stock.recipe_edit': false,
    'stock.inventory_count': false,
    'stock.supplier_payout': false,
    'stock.waste_report': false,
    'hr.staff_view': false,
    'hr.staff_create': false,
    'hr.staff_edit': false,
    'hr.staff_delete': false,
    'hr.contracts_manage': false,
    'hr.evaluations_create': false,
    'hr.evaluations_view': false,
    'hr.leaves_approve': false,
    'hr.leaves_create': false,
    'hr.attendance_view': false,
    'hr.attendance_edit': false,
    'hr.loans_approve': false,
    'hr.history_view': false,
    'hr.settings': false,
    'accounting.payroll_generate': false,
    'accounting.payroll_pay': false,
    'accounting.payroll_view': false,
    'accounting.closures_view': false,
    'accounting.closures_create': false,
    'accounting.payouts_manage': false,
    'accounting.taxes_export': false,
    'accounting.sales_journal': false,
    'accounting.expenses_create': false,
    'accounting.bank_reconciliation': false,
    'delivery.orders_view': true,
    'delivery.driver_assign': false,
    'delivery.gps_tracking': false,
    'delivery.pwa_access': false,
    'delivery.settings': false,
    'delivery.driver_payout': false,
    'delivery.status_override': false,
    'delivery.route_optimization': false,
    'loyalty.customers_view': true,
    'loyalty.customers_edit': true,
    'loyalty.points_add': false,
    'loyalty.points_reset': false,
    'loyalty.rewards_manage': false,
    'loyalty.promotions_manage': false,
    'loyalty.export': false,
    'booking.view': true,
    'booking.create': true,
    'booking.tables_manage': false,
    'booking.settings': false,
    'booking.cancel': false,
    'booking.check_in': true,
    'booking.notifications': false,
    'booking.history': false,
    'ecommerce.catalog_sync': false,
    'ecommerce.orders_view': false,
    'ecommerce.orders_accept': false,
    'ecommerce.settings': false,
    'ecommerce.delivery_fees': false,
    'ecommerce.analytics': false,
    'admin.users_manage': false,
    'admin.roles_permissions': false,
    'admin.store_edit': false,
    'admin.api_tokens': false,
    'admin.printers_manage': false,
    'admin.rounding_rules': false,
    'admin.security_settings': false,
    'admin.audit_logs': false,
    'admin.db_backup': false
  },
  SERVER: {
    POS_ACCESS: true,
    CASH_DRAWER_ACCESS: false,
    KDS_ACCESS: false,
    STOCK_ACCESS: false,
    STOCK_ADJUSTMENT: false,
    HR_ACCESS: false,
    ANALYTICS_ACCESS: false,
    CONFIG_ACCESS: false,
    'dashboard.view': false,
    'dashboard.read_analytics': false,
    'dashboard.margins': false,
    'dashboard.compare': false,
    'dashboard.export_pdf': false,
    'dashboard.export_excel': false,
    'pos.orders_view': true,
    'pos.orders_refund': false,
    'pos.discounts': false,
    'pos.gift_cards': false,
    'pos.shift_open': false,
    'pos.shift_close': false,
    'pos.split_bill': false,
    'pos.print_ticket': false,
    'pos.offline_mode': false,
    'pos.price_override': false,
    'pos.void_item': true,
    'pos.tax_exempt': false,
    'pos.customer_assign': true,
    'kds.orders_view': false,
    'kds.status_update': false,
    'kds.alert_send': false,
    'kds.history': false,
    'stock.supplier_create': false,
    'stock.po_create': false,
    'stock.po_receive': false,
    'stock.transfer': false,
    'stock.valuation': false,
    'stock.alerts_config': false,
    'stock.recipe_edit': false,
    'stock.inventory_count': false,
    'stock.supplier_payout': false,
    'stock.waste_report': false,
    'hr.staff_view': false,
    'hr.staff_create': false,
    'hr.staff_edit': false,
    'hr.staff_delete': false,
    'hr.contracts_manage': false,
    'hr.evaluations_create': false,
    'hr.evaluations_view': false,
    'hr.leaves_approve': false,
    'hr.leaves_create': false,
    'hr.attendance_view': false,
    'hr.attendance_edit': false,
    'hr.loans_approve': false,
    'hr.history_view': false,
    'hr.settings': false,
    'accounting.payroll_generate': false,
    'accounting.payroll_pay': false,
    'accounting.payroll_view': false,
    'accounting.closures_view': false,
    'accounting.closures_create': false,
    'accounting.payouts_manage': false,
    'accounting.taxes_export': false,
    'accounting.sales_journal': false,
    'accounting.expenses_create': false,
    'accounting.bank_reconciliation': false,
    'delivery.orders_view': false,
    'delivery.driver_assign': false,
    'delivery.gps_tracking': false,
    'delivery.pwa_access': false,
    'delivery.settings': false,
    'delivery.driver_payout': false,
    'delivery.status_override': false,
    'delivery.route_optimization': false,
    'loyalty.customers_view': true,
    'loyalty.customers_edit': false,
    'loyalty.points_add': false,
    'loyalty.points_reset': false,
    'loyalty.rewards_manage': false,
    'loyalty.promotions_manage': false,
    'loyalty.export': false,
    'booking.view': true,
    'booking.create': true,
    'booking.tables_manage': false,
    'booking.settings': false,
    'booking.cancel': false,
    'booking.check_in': true,
    'booking.notifications': false,
    'booking.history': false,
    'ecommerce.catalog_sync': false,
    'ecommerce.orders_view': false,
    'ecommerce.orders_accept': false,
    'ecommerce.settings': false,
    'ecommerce.delivery_fees': false,
    'ecommerce.analytics': false,
    'admin.users_manage': false,
    'admin.roles_permissions': false,
    'admin.store_edit': false,
    'admin.api_tokens': false,
    'admin.printers_manage': false,
    'admin.rounding_rules': false,
    'admin.security_settings': false,
    'admin.audit_logs': false,
    'admin.db_backup': false
  },
  KITCHEN: {
    POS_ACCESS: false,
    CASH_DRAWER_ACCESS: false,
    KDS_ACCESS: true,
    STOCK_ACCESS: false,
    STOCK_ADJUSTMENT: false,
    HR_ACCESS: false,
    ANALYTICS_ACCESS: false,
    CONFIG_ACCESS: false,
    'dashboard.view': false,
    'dashboard.read_analytics': false,
    'dashboard.margins': false,
    'dashboard.compare': false,
    'dashboard.export_pdf': false,
    'dashboard.export_excel': false,
    'pos.orders_view': false,
    'pos.orders_refund': false,
    'pos.discounts': false,
    'pos.gift_cards': false,
    'pos.shift_open': false,
    'pos.shift_close': false,
    'pos.split_bill': false,
    'pos.print_ticket': false,
    'pos.offline_mode': false,
    'pos.price_override': false,
    'pos.void_item': false,
    'pos.tax_exempt': false,
    'pos.customer_assign': false,
    'kds.orders_view': true,
    'kds.status_update': true,
    'kds.alert_send': true,
    'kds.history': true,
    'stock.supplier_create': false,
    'stock.po_create': false,
    'stock.po_receive': false,
    'stock.transfer': false,
    'stock.valuation': false,
    'stock.alerts_config': false,
    'stock.recipe_edit': false,
    'stock.inventory_count': false,
    'stock.supplier_payout': false,
    'stock.waste_report': false,
    'hr.staff_view': false,
    'hr.staff_create': false,
    'hr.staff_edit': false,
    'hr.staff_delete': false,
    'hr.contracts_manage': false,
    'hr.evaluations_create': false,
    'hr.evaluations_view': false,
    'hr.leaves_approve': false,
    'hr.leaves_create': false,
    'hr.attendance_view': false,
    'hr.attendance_edit': false,
    'hr.loans_approve': false,
    'hr.history_view': false,
    'hr.settings': false,
    'accounting.payroll_generate': false,
    'accounting.payroll_pay': false,
    'accounting.payroll_view': false,
    'accounting.closures_view': false,
    'accounting.closures_create': false,
    'accounting.payouts_manage': false,
    'accounting.taxes_export': false,
    'accounting.sales_journal': false,
    'accounting.expenses_create': false,
    'accounting.bank_reconciliation': false,
    'delivery.orders_view': false,
    'delivery.driver_assign': false,
    'delivery.gps_tracking': false,
    'delivery.pwa_access': false,
    'delivery.settings': false,
    'delivery.driver_payout': false,
    'delivery.status_override': false,
    'delivery.route_optimization': false,
    'loyalty.customers_view': false,
    'loyalty.customers_edit': false,
    'loyalty.points_add': false,
    'loyalty.points_reset': false,
    'loyalty.rewards_manage': false,
    'loyalty.promotions_manage': false,
    'loyalty.export': false,
    'booking.view': false,
    'booking.create': false,
    'booking.tables_manage': false,
    'booking.settings': false,
    'booking.cancel': false,
    'booking.check_in': false,
    'booking.notifications': false,
    'booking.history': false,
    'ecommerce.catalog_sync': false,
    'ecommerce.orders_view': false,
    'ecommerce.orders_accept': false,
    'ecommerce.settings': false,
    'ecommerce.delivery_fees': false,
    'ecommerce.analytics': false,
    'admin.users_manage': false,
    'admin.roles_permissions': false,
    'admin.store_edit': false,
    'admin.api_tokens': false,
    'admin.printers_manage': false,
    'admin.rounding_rules': false,
    'admin.security_settings': false,
    'admin.audit_logs': false,
    'admin.db_backup': false
  },
  DELIVERY: {
    POS_ACCESS: true,
    CASH_DRAWER_ACCESS: false,
    KDS_ACCESS: false,
    STOCK_ACCESS: false,
    STOCK_ADJUSTMENT: false,
    HR_ACCESS: false,
    ANALYTICS_ACCESS: false,
    CONFIG_ACCESS: false,
    'dashboard.view': false,
    'dashboard.read_analytics': false,
    'dashboard.margins': false,
    'dashboard.compare': false,
    'dashboard.export_pdf': false,
    'dashboard.export_excel': false,
    'pos.orders_view': true,
    'pos.orders_refund': false,
    'pos.discounts': false,
    'pos.gift_cards': false,
    'pos.shift_open': false,
    'pos.shift_close': false,
    'pos.split_bill': false,
    'pos.print_ticket': false,
    'pos.offline_mode': false,
    'pos.price_override': false,
    'pos.void_item': false,
    'pos.tax_exempt': false,
    'pos.customer_assign': true,
    'kds.orders_view': false,
    'kds.status_update': false,
    'kds.alert_send': false,
    'kds.history': false,
    'stock.supplier_create': false,
    'stock.po_create': false,
    'stock.po_receive': false,
    'stock.transfer': false,
    'stock.valuation': false,
    'stock.alerts_config': false,
    'stock.recipe_edit': false,
    'stock.inventory_count': false,
    'stock.supplier_payout': false,
    'stock.waste_report': false,
    'hr.staff_view': false,
    'hr.staff_create': false,
    'hr.staff_edit': false,
    'hr.staff_delete': false,
    'hr.contracts_manage': false,
    'hr.evaluations_create': false,
    'hr.evaluations_view': false,
    'hr.leaves_approve': false,
    'hr.leaves_create': false,
    'hr.attendance_view': false,
    'hr.attendance_edit': false,
    'hr.loans_approve': false,
    'hr.history_view': false,
    'hr.settings': false,
    'accounting.payroll_generate': false,
    'accounting.payroll_pay': false,
    'accounting.payroll_view': false,
    'accounting.closures_view': false,
    'accounting.closures_create': false,
    'accounting.payouts_manage': false,
    'accounting.taxes_export': false,
    'accounting.sales_journal': false,
    'accounting.expenses_create': false,
    'accounting.bank_reconciliation': false,
    'delivery.orders_view': true,
    'delivery.driver_assign': true,
    'delivery.gps_tracking': true,
    'delivery.pwa_access': false,
    'delivery.settings': false,
    'delivery.driver_payout': false,
    'delivery.status_override': true,
    'delivery.route_optimization': true,
    'loyalty.customers_view': true,
    'loyalty.customers_edit': false,
    'loyalty.points_add': false,
    'loyalty.points_reset': false,
    'loyalty.rewards_manage': false,
    'loyalty.promotions_manage': false,
    'loyalty.export': false,
    'booking.view': false,
    'booking.create': false,
    'booking.tables_manage': false,
    'booking.settings': false,
    'booking.cancel': false,
    'booking.check_in': false,
    'booking.notifications': false,
    'booking.history': false,
    'ecommerce.catalog_sync': false,
    'ecommerce.orders_view': true,
    'ecommerce.orders_accept': false,
    'ecommerce.settings': false,
    'ecommerce.delivery_fees': false,
    'ecommerce.analytics': false,
    'admin.users_manage': false,
    'admin.roles_permissions': false,
    'admin.store_edit': false,
    'admin.api_tokens': false,
    'admin.printers_manage': false,
    'admin.rounding_rules': false,
    'admin.security_settings': false,
    'admin.audit_logs': false,
    'admin.db_backup': false
  },
  LIVREUR: {
    POS_ACCESS: true,
    CASH_DRAWER_ACCESS: false,
    KDS_ACCESS: false,
    STOCK_ACCESS: false,
    STOCK_ADJUSTMENT: false,
    HR_ACCESS: false,
    ANALYTICS_ACCESS: false,
    CONFIG_ACCESS: false,
    'dashboard.view': false,
    'dashboard.read_analytics': false,
    'dashboard.margins': false,
    'dashboard.compare': false,
    'dashboard.export_pdf': false,
    'dashboard.export_excel': false,
    'pos.orders_view': false,
    'pos.orders_refund': false,
    'pos.discounts': false,
    'pos.gift_cards': false,
    'pos.shift_open': false,
    'pos.shift_close': false,
    'pos.split_bill': false,
    'pos.print_ticket': false,
    'pos.offline_mode': false,
    'pos.price_override': false,
    'pos.void_item': false,
    'pos.tax_exempt': false,
    'pos.customer_assign': false,
    'kds.orders_view': false,
    'kds.status_update': false,
    'kds.alert_send': false,
    'kds.history': false,
    'stock.supplier_create': false,
    'stock.po_create': false,
    'stock.po_receive': false,
    'stock.transfer': false,
    'stock.valuation': false,
    'stock.alerts_config': false,
    'stock.recipe_edit': false,
    'stock.inventory_count': false,
    'stock.supplier_payout': false,
    'stock.waste_report': false,
    'hr.staff_view': false,
    'hr.staff_create': false,
    'hr.staff_edit': false,
    'hr.staff_delete': false,
    'hr.contracts_manage': false,
    'hr.evaluations_create': false,
    'hr.evaluations_view': false,
    'hr.leaves_approve': false,
    'hr.leaves_create': false,
    'hr.attendance_view': false,
    'hr.attendance_edit': false,
    'hr.loans_approve': false,
    'hr.history_view': false,
    'hr.settings': false,
    'accounting.payroll_generate': false,
    'accounting.payroll_pay': false,
    'accounting.payroll_view': false,
    'accounting.closures_view': false,
    'accounting.closures_create': false,
    'accounting.payouts_manage': false,
    'accounting.taxes_export': false,
    'accounting.sales_journal': false,
    'accounting.expenses_create': false,
    'accounting.bank_reconciliation': false,
    'delivery.orders_view': true,
    'delivery.driver_assign': false,
    'delivery.gps_tracking': false,
    'delivery.pwa_access': true,
    'delivery.settings': false,
    'delivery.driver_payout': false,
    'delivery.status_override': false,
    'delivery.route_optimization': false,
    'loyalty.customers_view': false,
    'loyalty.customers_edit': false,
    'loyalty.points_add': false,
    'loyalty.points_reset': false,
    'loyalty.rewards_manage': false,
    'loyalty.promotions_manage': false,
    'loyalty.export': false,
    'booking.view': false,
    'booking.create': false,
    'booking.tables_manage': false,
    'booking.settings': false,
    'booking.cancel': false,
    'booking.check_in': false,
    'booking.notifications': false,
    'booking.history': false,
    'ecommerce.catalog_sync': false,
    'ecommerce.orders_view': false,
    'ecommerce.orders_accept': false,
    'ecommerce.settings': false,
    'ecommerce.delivery_fees': false,
    'ecommerce.analytics': false,
    'admin.users_manage': false,
    'admin.roles_permissions': false,
    'admin.store_edit': false,
    'admin.api_tokens': false,
    'admin.printers_manage': false,
    'admin.rounding_rules': false,
    'admin.security_settings': false,
    'admin.audit_logs': false,
    'admin.db_backup': false
  },
  ADMIN: {
    POS_ACCESS: true,
    CASH_DRAWER_ACCESS: true,
    KDS_ACCESS: true,
    STOCK_ACCESS: true,
    STOCK_ADJUSTMENT: true,
    HR_ACCESS: true,
    ANALYTICS_ACCESS: true,
    CONFIG_ACCESS: true,
    'dashboard.view': true,
    'dashboard.read_analytics': true,
    'dashboard.margins': true,
    'dashboard.compare': true,
    'dashboard.export_pdf': true,
    'dashboard.export_excel': true,
    'pos.orders_view': true,
    'pos.orders_refund': true,
    'pos.discounts': true,
    'pos.gift_cards': true,
    'pos.shift_open': true,
    'pos.shift_close': true,
    'pos.split_bill': true,
    'pos.print_ticket': true,
    'pos.offline_mode': true,
    'pos.price_override': true,
    'pos.void_item': true,
    'pos.tax_exempt': true,
    'pos.customer_assign': true,
    'kds.orders_view': true,
    'kds.status_update': true,
    'kds.alert_send': true,
    'kds.history': true,
    'stock.supplier_create': true,
    'stock.po_create': true,
    'stock.po_receive': true,
    'stock.transfer': true,
    'stock.valuation': true,
    'stock.alerts_config': true,
    'stock.recipe_edit': true,
    'stock.inventory_count': true,
    'stock.supplier_payout': true,
    'stock.waste_report': true,
    'hr.staff_view': true,
    'hr.staff_create': true,
    'hr.staff_edit': true,
    'hr.staff_delete': true,
    'hr.contracts_manage': true,
    'hr.evaluations_create': true,
    'hr.evaluations_view': true,
    'hr.leaves_approve': true,
    'hr.leaves_create': true,
    'hr.attendance_view': true,
    'hr.attendance_edit': true,
    'hr.loans_approve': true,
    'hr.history_view': true,
    'hr.settings': true,
    'accounting.payroll_generate': true,
    'accounting.payroll_pay': true,
    'accounting.payroll_view': true,
    'accounting.closures_view': true,
    'accounting.closures_create': true,
    'accounting.payouts_manage': true,
    'accounting.taxes_export': true,
    'accounting.sales_journal': true,
    'accounting.expenses_create': true,
    'accounting.bank_reconciliation': true,
    'delivery.orders_view': true,
    'delivery.driver_assign': true,
    'delivery.gps_tracking': true,
    'delivery.pwa_access': true,
    'delivery.settings': true,
    'delivery.driver_payout': true,
    'delivery.status_override': true,
    'delivery.route_optimization': true,
    'loyalty.customers_view': true,
    'loyalty.customers_edit': true,
    'loyalty.points_add': true,
    'loyalty.points_reset': true,
    'loyalty.rewards_manage': true,
    'loyalty.promotions_manage': true,
    'loyalty.export': true,
    'booking.view': true,
    'booking.create': true,
    'booking.tables_manage': true,
    'booking.settings': true,
    'booking.cancel': true,
    'booking.check_in': true,
    'booking.notifications': true,
    'booking.history': true,
    'ecommerce.catalog_sync': true,
    'ecommerce.orders_view': true,
    'ecommerce.orders_accept': true,
    'ecommerce.settings': true,
    'ecommerce.delivery_fees': true,
    'ecommerce.analytics': true,
    'admin.users_manage': true,
    'admin.roles_permissions': true,
    'admin.store_edit': true,
    'admin.api_tokens': true,
    'admin.printers_manage': true,
    'admin.rounding_rules': true,
    'admin.security_settings': true,
    'admin.audit_logs': true,
    'admin.db_backup': true
  },
  SUPER_ADMIN: {
    POS_ACCESS: true,
    CASH_DRAWER_ACCESS: true,
    KDS_ACCESS: true,
    STOCK_ACCESS: true,
    STOCK_ADJUSTMENT: true,
    HR_ACCESS: true,
    ANALYTICS_ACCESS: true,
    CONFIG_ACCESS: true,
    'dashboard.view': true,
    'dashboard.read_analytics': true,
    'dashboard.margins': true,
    'dashboard.compare': true,
    'dashboard.export_pdf': true,
    'dashboard.export_excel': true,
    'pos.orders_view': true,
    'pos.orders_refund': true,
    'pos.discounts': true,
    'pos.gift_cards': true,
    'pos.shift_open': true,
    'pos.shift_close': true,
    'pos.split_bill': true,
    'pos.print_ticket': true,
    'pos.offline_mode': true,
    'pos.price_override': true,
    'pos.void_item': true,
    'pos.tax_exempt': true,
    'pos.customer_assign': true,
    'kds.orders_view': true,
    'kds.status_update': true,
    'kds.alert_send': true,
    'kds.history': true,
    'stock.supplier_create': true,
    'stock.po_create': true,
    'stock.po_receive': true,
    'stock.transfer': true,
    'stock.valuation': true,
    'stock.alerts_config': true,
    'stock.recipe_edit': true,
    'stock.inventory_count': true,
    'stock.supplier_payout': true,
    'stock.waste_report': true,
    'hr.staff_view': true,
    'hr.staff_create': true,
    'hr.staff_edit': true,
    'hr.staff_delete': true,
    'hr.contracts_manage': true,
    'hr.evaluations_create': true,
    'hr.evaluations_view': true,
    'hr.leaves_approve': true,
    'hr.leaves_create': true,
    'hr.attendance_view': true,
    'hr.attendance_edit': true,
    'hr.loans_approve': true,
    'hr.history_view': true,
    'hr.settings': true,
    'accounting.payroll_generate': true,
    'accounting.payroll_pay': true,
    'accounting.payroll_view': true,
    'accounting.closures_view': true,
    'accounting.closures_create': true,
    'accounting.payouts_manage': true,
    'accounting.taxes_export': true,
    'accounting.sales_journal': true,
    'accounting.expenses_create': true,
    'accounting.bank_reconciliation': true,
    'delivery.orders_view': true,
    'delivery.driver_assign': true,
    'delivery.gps_tracking': true,
    'delivery.pwa_access': true,
    'delivery.settings': true,
    'delivery.driver_payout': true,
    'delivery.status_override': true,
    'delivery.route_optimization': true,
    'loyalty.customers_view': true,
    'loyalty.customers_edit': true,
    'loyalty.points_add': true,
    'loyalty.points_reset': true,
    'loyalty.rewards_manage': true,
    'loyalty.promotions_manage': true,
    'loyalty.export': true,
    'booking.view': true,
    'booking.create': true,
    'booking.tables_manage': true,
    'booking.settings': true,
    'booking.cancel': true,
    'booking.check_in': true,
    'booking.notifications': true,
    'booking.history': true,
    'ecommerce.catalog_sync': true,
    'ecommerce.orders_view': true,
    'ecommerce.orders_accept': true,
    'ecommerce.settings': true,
    'ecommerce.delivery_fees': true,
    'ecommerce.analytics': true,
    'admin.users_manage': true,
    'admin.roles_permissions': true,
    'admin.store_edit': true,
    'admin.api_tokens': true,
    'admin.printers_manage': true,
    'admin.rounding_rules': true,
    'admin.security_settings': true,
    'admin.audit_logs': true,
    'admin.db_backup': true
  },
  STORE_MANAGER: {
    POS_ACCESS: true,
    CASH_DRAWER_ACCESS: true,
    KDS_ACCESS: true,
    STOCK_ACCESS: true,
    STOCK_ADJUSTMENT: true,
    HR_ACCESS: true,
    ANALYTICS_ACCESS: true,
    CONFIG_ACCESS: false,
    'dashboard.view': true,
    'dashboard.read_analytics': true,
    'dashboard.margins': true,
    'dashboard.compare': true,
    'dashboard.export_pdf': true,
    'dashboard.export_excel': true,
    'pos.orders_view': true,
    'pos.orders_refund': true,
    'pos.discounts': true,
    'pos.gift_cards': true,
    'pos.shift_open': true,
    'pos.shift_close': true,
    'pos.split_bill': true,
    'pos.print_ticket': true,
    'pos.offline_mode': true,
    'pos.price_override': true,
    'pos.void_item': true,
    'pos.tax_exempt': true,
    'pos.customer_assign': true,
    'kds.orders_view': true,
    'kds.status_update': true,
    'kds.alert_send': true,
    'kds.history': true,
    'stock.supplier_create': true,
    'stock.po_create': true,
    'stock.po_receive': true,
    'stock.transfer': true,
    'stock.valuation': true,
    'stock.alerts_config': true,
    'stock.recipe_edit': true,
    'stock.inventory_count': true,
    'stock.supplier_payout': true,
    'stock.waste_report': true,
    'hr.staff_view': true,
    'hr.staff_create': true,
    'hr.staff_edit': true,
    'hr.staff_delete': false,
    'hr.contracts_manage': true,
    'hr.evaluations_create': true,
    'hr.evaluations_view': true,
    'hr.leaves_approve': true,
    'hr.leaves_create': true,
    'hr.attendance_view': true,
    'hr.attendance_edit': true,
    'hr.loans_approve': true,
    'hr.history_view': true,
    'hr.settings': false,
    'accounting.payroll_generate': false,
    'accounting.payroll_pay': false,
    'accounting.payroll_view': true,
    'accounting.closures_view': true,
    'accounting.closures_create': false,
    'accounting.payouts_manage': true,
    'accounting.taxes_export': false,
    'accounting.sales_journal': true,
    'accounting.expenses_create': true,
    'accounting.bank_reconciliation': false,
    'delivery.orders_view': true,
    'delivery.driver_assign': true,
    'delivery.gps_tracking': true,
    'delivery.pwa_access': true,
    'delivery.settings': false,
    'delivery.driver_payout': true,
    'delivery.status_override': true,
    'delivery.route_optimization': true,
    'loyalty.customers_view': true,
    'loyalty.customers_edit': true,
    'loyalty.points_add': true,
    'loyalty.points_reset': false,
    'loyalty.rewards_manage': true,
    'loyalty.promotions_manage': true,
    'loyalty.export': true,
    'booking.view': true,
    'booking.create': true,
    'booking.tables_manage': true,
    'booking.settings': true,
    'booking.cancel': true,
    'booking.check_in': true,
    'booking.notifications': true,
    'booking.history': true,
    'ecommerce.catalog_sync': true,
    'ecommerce.orders_view': true,
    'ecommerce.orders_accept': true,
    'ecommerce.settings': false,
    'ecommerce.delivery_fees': false,
    'ecommerce.analytics': true,
    'admin.users_manage': false,
    'admin.roles_permissions': false,
    'admin.store_edit': false,
    'admin.api_tokens': false,
    'admin.printers_manage': true,
    'admin.rounding_rules': false,
    'admin.security_settings': false,
    'admin.audit_logs': true,
    'admin.db_backup': false
  },
  STORE_EMPLOYEE: {
    POS_ACCESS: true,
    CASH_DRAWER_ACCESS: true,
    KDS_ACCESS: true,
    STOCK_ACCESS: false,
    STOCK_ADJUSTMENT: false,
    HR_ACCESS: false,
    ANALYTICS_ACCESS: false,
    CONFIG_ACCESS: false,
    'dashboard.view': false,
    'dashboard.read_analytics': false,
    'dashboard.margins': false,
    'dashboard.compare': false,
    'dashboard.export_pdf': false,
    'dashboard.export_excel': false,
    'pos.orders_view': true,
    'pos.orders_refund': false,
    'pos.discounts': false,
    'pos.gift_cards': false,
    'pos.shift_open': true,
    'pos.shift_close': true,
    'pos.split_bill': true,
    'pos.print_ticket': true,
    'pos.offline_mode': true,
    'pos.price_override': false,
    'pos.void_item': true,
    'pos.tax_exempt': false,
    'pos.customer_assign': true,
    'kds.orders_view': true,
    'kds.status_update': true,
    'kds.alert_send': false,
    'kds.history': true,
    'stock.supplier_create': false,
    'stock.po_create': false,
    'stock.po_receive': false,
    'stock.transfer': false,
    'stock.valuation': false,
    'stock.alerts_config': false,
    'stock.recipe_edit': false,
    'stock.inventory_count': false,
    'stock.supplier_payout': false,
    'stock.waste_report': false,
    'hr.staff_view': false,
    'hr.staff_create': false,
    'hr.staff_edit': false,
    'hr.staff_delete': false,
    'hr.contracts_manage': false,
    'hr.evaluations_create': false,
    'hr.evaluations_view': false,
    'hr.leaves_approve': false,
    'hr.leaves_create': false,
    'hr.attendance_view': false,
    'hr.attendance_edit': false,
    'hr.loans_approve': false,
    'hr.history_view': false,
    'hr.settings': false,
    'accounting.payroll_generate': false,
    'accounting.payroll_pay': false,
    'accounting.payroll_view': false,
    'accounting.closures_view': false,
    'accounting.closures_create': false,
    'accounting.payouts_manage': false,
    'accounting.taxes_export': false,
    'accounting.sales_journal': false,
    'accounting.expenses_create': false,
    'accounting.bank_reconciliation': false,
    'delivery.orders_view': false,
    'delivery.driver_assign': false,
    'delivery.gps_tracking': false,
    'delivery.pwa_access': false,
    'delivery.settings': false,
    'delivery.driver_payout': false,
    'delivery.status_override': false,
    'delivery.route_optimization': false,
    'loyalty.customers_view': true,
    'loyalty.customers_edit': false,
    'loyalty.points_add': false,
    'loyalty.points_reset': false,
    'loyalty.rewards_manage': false,
    'loyalty.promotions_manage': false,
    'loyalty.export': false,
    'booking.view': true,
    'booking.create': true,
    'booking.tables_manage': false,
    'booking.settings': false,
    'booking.cancel': false,
    'booking.check_in': true,
    'booking.notifications': false,
    'booking.history': false,
    'ecommerce.catalog_sync': false,
    'ecommerce.orders_view': false,
    'ecommerce.orders_accept': false,
    'ecommerce.settings': false,
    'ecommerce.delivery_fees': false,
    'ecommerce.analytics': false,
    'admin.users_manage': false,
    'admin.roles_permissions': false,
    'admin.store_edit': false,
    'admin.api_tokens': false,
    'admin.printers_manage': false,
    'admin.rounding_rules': false,
    'admin.security_settings': false,
    'admin.audit_logs': false,
    'admin.db_backup': false
  }
}
